steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '--no-cache'
      - '-t'
      - 'gcr.io/$PROJECT_ID/futfun-backend:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/futfun-backend:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'gcr.io/$PROJECT_ID/futfun-backend:$BUILD_ID'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'gcr.io/$PROJECT_ID/futfun-backend:latest'

images:
  - 'gcr.io/$PROJECT_ID/futfun-backend:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/futfun-backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
